config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope :monitoring do
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'admin' && password == 'password'
    end
    mount Sidekiq::Web, at: "/sidekiq"
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get "password_resets/new"
  get "password_resets/edit"
  # get "comment/index"
  resources :microposts do
    post "/react" => "microposts#react"
    resources :comments, only: [ :create ] do
      post "/reply" => "comments#create"
    end
  end
  resources :users do
    get "microposts" => "users#find_by_user"
    member do
      get :following, :followers
    end
    resources :messages, only: [ :index, :create, :destroy ]
  end
  resources :relationships, only: [ :create, :destroy ]
  root "static_pages#home"
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "test" => "static_pages#test"
  get "/signup" => "users#new"
  # login routes
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :microposts, only: [ :create, :destroy ]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
# User model
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [ :google_oauth2, :github, :facebook ]
  has_many :providers, dependent: :destroy
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :reactions

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save { self.email = email.downcase }
  before_create :create_activation_digest

  validates :name, presence: true, length: { in: 6..255 }
  validates :email, presence: true,
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: { case_sensitive: true }
  validates :password, length: { minimum: 6 }, presence: true, allow_nil: true

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
      WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
      OR user_id = :user_id", user_id: id)
  end

  def follow(other_user)
    following << other_user
  end
  def unfollow(other_user)
  following.delete(other_user)
  end
  # Returns true if the current user is following the other user.
  def following?(other_user)
  following.include?(other_user)
  end

  def activate
    update_columns(activated: FILL_IN, activated_at: FILL_IN)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end


  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64 || "Test remember token"
    end
  end

  private
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include SessionsHelper

  def facebook
    user = OmniauthService.from_omniauth(auth)
    login_redirect(user, "Facebook")
  end

  def github
    user = OmniauthService.from_omniauth(auth)
    login_redirect(user, "Github")
  end

  def google_oauth2
    user = OmniauthService.from_omniauth(auth)
    login_redirect(user, "Google")
  end

  def failure
    redirect_to root_path, event: :unprocessable_entity
  end

  private
  def login_redirect(user, kind_sso)
    if user&.persisted?
      log_in(user)
      flash[:notice] = t "devise.omniauth_callbacks.success", kind: kind_sso
      redirect_to user_url(user.id), event: :authentication
    else
      flash[:alert] = t "devise.omniauth_callbacks.failure", kind: kind_sso, reason: "#{auth.info.email} is not authorized."
      failure
    end
  end

  def auth
    @auth ||= request.env["omniauth.auth"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :logged_in_user, only: [ :edit, :update, :show, :index ]
  before_action :correct_user, only: [ :edit, :update ]
  before_action :admin_user, only: [ :destroy ]
  before_action :logged_in_user, only: [ :index, :edit, :update, :destroy ]

  include SessionsHelper

  # GET /users or /users.json
  def index
    # @users = User.all
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  # GET /users/1 or /users/1.json
  def show
    flash.now[:success] = "WELCOM TO THE SAMPLE APP!"
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.account_activation(@user).deliver_now
        flash[:info] = "Please check your email to activate your account."
        format.html { render :new }
        format.json { render :show, status: :created, location: @user }
      else
        flash[:info] = "Sign up fail"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update(user_params)
        flash.now[:success] = "Update profile sucessfully"
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def find_by_user
    @microposts = Micropost.find_by!(user_id: params[:user_id])
    render json: @microposts
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render "show_follow"
  end
    def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render "show_follow"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :age, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 20 })
    gravatar_url = "https://cdn.pixabay.com/photo/2021/11/12/03/04/woman-6787784_1280.png"
    image_tag(gravatar_url, size: 30, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
<div><%= hidden_field_tag :followed_id, @user.id %></div>
<%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div class="errors">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, "New password (optional)", style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, "Confirm new password (optional)", style: "display: block" %>
    <%= form.text_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
html: { method: :delete }, remote: true) do |f| %>
<%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= user.age %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= user.created_at %>
  </p>
  <p>
    <strong>Updated at:</strong>
    <%= user.updated_at %>
  </p>
  <p> <%=Time.now%> </p>
</div>

app/views/users/_user_paging.html.erb
<%= gravatar_for user, size: 50 %>
<%= link_to user.name, user %>
<% if current_user.admin? && !current_user?(user) %>
  | <%= link_to "delete", user,
    data: {turbo_method: :delete,  turbo_confirm: "You sure?" } %>
<% end %>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p class="notice"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <ul class="users">
    <% @users.each do |user| %>
    <li>
      <%= render partial: "user_paging", locals: {user: user} %>
    </li> 
    <% end %>
  </ul>
  <%= will_paginate @clients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_with(model: @user, local: true) do |f| %>
    <%= render "shared/errors", object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Create my account", class: "btn btn-primary" %>
  <% end %>
  </div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p class="notice"><%= notice %></p>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <div style="display: flex">
      <%= render 'follow_form' if logged_in? %>
      <div class="message_link-container">
        <%= link_to "Messages",  user_messages_path(@user), class: "message-link" %>
      </div>
    </div>

  <% if @user.microposts.any? %>
    <h3>Microposts (<%= @user.microposts.count %>)</h3>
    <%= will_paginate @microposts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    <ol class="microposts">
    <%= render @microposts %>
    </ol>
    <%= will_paginate @microposts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
<aside class="col-md-4">
<section class="user_info">
<%= gravatar_for @user %>
<h1><%= @user.name %></h1>
<span><%= link_to "view my profile", @user %></span>
<span><b>Microposts:</b> <%= @user.microposts.count %></span>
</section>
<section class="stats">
<%= render 'shared/stats' %>
<% if @users.any? %>
<div class="user_avatars">
<% @users.each do |user| %>
<%= link_to gravatar_for(user, size: 30), user %>
<% end %>
</div>
<% end %>
</section>
</aside>
<div class="col-md-8">
<h3><%= @title %></h3>
<% if @users.any? %>
<ul class="users follow">
<%= render @users %>
</ul>
<%= will_paginate %>
<% end %>
</div>
</div>