config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope :monitoring do
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'admin' && password == 'password'
    end
    mount Sidekiq::Web, at: "/sidekiq"
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get "password_resets/new"
  get "password_resets/edit"
  # get "comment/index"
  resources :microposts do
    post "/react" => "microposts#react"
    resources :comments, only: [ :create ] do
      post "/reply" => "comments#create"
    end
  end
  resources :users do
    get "microposts" => "users#find_by_user"
    member do
      get :following, :followers
    end
    resources :messages, only: [ :index, :create, :destroy ]
  end
  resources :relationships, only: [ :create, :destroy ]
  root "static_pages#home"
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "test" => "static_pages#test"
  get "/signup" => "users#new"
  # login routes
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :microposts, only: [ :create, :destroy ]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_comment.html.erb
<%= turbo_frame_tag("comments_#{micropost.id}") do %>
  <div class="comment-container" id="comment-<%= micropost.id %>" data-controller="comment">
    <div class="comment-body">
      <span class="user">
      <%= link_to micropost.user.name, micropost.user %>
    </span>
      <span class="timestamp">
      At <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
      <p class="content micropost-content">
        <%= micropost.content %>
      </p>
    </div>
    <div class="comment-bottom">
      <div class="left flex">
        <div class="flex">
          <%= render "shared/reaction_form", micropost: micropost %>
        </div>
        <button class="reply-btn" data-comment-target="replyButton" data-action="click->comment#reply_toggle">
          Reply
        </button>
      </div>
      <div class="right">
        <div class="flex">
          <div class="reactions-stats" >
            <%= render "shared/reaction_stats", micropost: micropost %>
          </div>
        </div>
      </div>
    </div>
    <div>
      <% if micropost.comments.size > 0 %>
        <button class="reply-btn" data-comment-target="repliesButton" data-action="click->comment#show_replies">
          Hide <%= micropost.comments.size %> replies
        </button>
      <% end %>
    </div>
    <div class="reply-container-form" data-comment-target="replyForm">
      <%= render "shared/reply_form", micropost: micropost %>
    </div>
    <div class="replies-container" data-comment-target="replies">
      <div id="microposts">
        <% micropost.comments.each do |comment| %>
          <%= render "shared/reply", micropost: comment %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_comment_form.html.erb
<%= form_with(model: @micropost,
              url: micropost_comments_url(@micropost),
              data: { controller: "comment", action: "turbo:submit-end->comment#clearTextarea" },
              method: :post, class: 'comment-form', id: 'comment-form') do |f| %>
  <div class="field comment-input comment-box" data-comment-target="form">
    <%= f.text_area :content, value: "",
                    class: "comment-input input-comment-reply", id: "input-comment",
                    placeholder: "Comment here...",
                    data: { comment_target: "textarea" }
    %>
    <div class="button-container">
      <%= f.submit "Comment", class: "comment-button", id: "button-submit" %>
    </div>
  </div>
  <div>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, params: { controller: :static_pages, action: :home } %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%= render 'shared/errors', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="image">
    <%= f.file_field :images, accept: "image/jpeg,image/gif,image/png", id: "micropost-image-input"%>
  </span>
  <span class="image">
    <%= f.file_field :images, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <span class="image">
    <%= f.file_field :file, accept: "pdf" %>
  </span>
<% end %>

app/views/shared/_reaction_button.html.erb
<%= button_to micropost_react_path(micropost.id),
              params: { reaction_type: reaction },
              class: "reaction-icon #{reaction} #{'active' if active}" do %>
  <i class="fa-regular fa-face-<%= reaction_icon(reaction) %>"></i>
<% end %>

app/views/shared/_reaction_form.html.erb
<%= turbo_frame_tag "reaction_form_#{micropost.id}", class: "flex" do %>
  <button class="reply-btn reaction-icon <%= active_reaction_class(micropost, current_user) %> active" id="love-btn">
    <%= active_reaction_text(micropost, current_user) || 'Love' %>
  </button>

  <div class="react-comment-container">
    <% %w(love sad angry).each do |reaction| %>
      <%= render 'shared/reaction_button', micropost: micropost, reaction: reaction, active: current_user_react(micropost, current_user, reaction) %>
    <% end %>
  </div>
<% end %>

app/views/shared/_reaction_stats.html.erb
<%= turbo_frame_tag "reactions_micropost_#{micropost.id}" do %>
  <div class="flex">
    <% if micropost.reactions.reaction_type_love.count > 0%>
      <div class="reaction-stats love" >
        <i class="fa-regular fa-face-grin-hearts"></i>
        <span><%= micropost.reactions.reaction_type_love.count %></span>
      </div>
    <% end %>
    <% if micropost.reactions.reaction_type_sad.count > 0 %>
      <div class="reaction-stats sad" >
        <i class="fa-regular fa-face-frown"></i>
        <span><%= micropost.reactions.reaction_type_sad.count %></span>
      </div>
    <% end %>
    <% if micropost.reactions.reaction_type_angry.count > 0 %>
      <div class="reaction-stats angry" >
        <i class="fa-regular fa-face-angry"></i>
        <span><%= micropost.reactions.reaction_type_angry.count %></span>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_reply.html.erb
<%= turbo_frame_tag("comments_#{micropost.id}") do %>
<div id="comment-<%= micropost.id %>" >
  <div class="comment-body reply-body">
      <span class="user">
      <%= link_to micropost.user.name, micropost.user %>
    </span>
    <span class="timestamp" >
      At <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
    <p class="content micropost-content">
      <%= micropost.content %>
    </p>
  </div>
  <div class="comment-bottom">
    <div class="flex">
      <%= render "shared/reaction_form", micropost: micropost %>
    </div>
    <div class="right">
      <div class="flex">
        <div class="reactions-stats" >
          <%= render "shared/reaction_stats", micropost: micropost %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_reply_form.html.erb
<% if micropost.parent_id.present? %>
  <%= form_with(model: @micropost,
                url:  micropost_comment_reply_url(micropost_id: micropost.parent_id, comment_id: micropost.id),
                method: :post, local: false, class: 'comment-form reply-form') do |f| %>
    <div class="field comment-input comment-box">
      <%= f.text_area :content, value: "",  class: "comment-input input-comment-reply", placeholder: "Comment here..."%>
      <div class="button-container">
        <%= f.submit "Comment", class: "comment-button ", id: "button-submit" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
<a href="<%= following_user_path(@user) %>">
<strong id="following" class="stat">
<%= @user.following.count %>
</strong>
following
</a>
<a href="<%= followers_user_path(@user) %>">
<strong id="followers" class="stat">
<%= @user.followers.count %>
</strong>
followers
</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>