config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope :monitoring do
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'admin' && password == 'password'
    end
    mount Sidekiq::Web, at: "/sidekiq"
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get "password_resets/new"
  get "password_resets/edit"
  # get "comment/index"
  resources :microposts do
    post "/react" => "microposts#react"
    resources :comments, only: [ :create ] do
      post "/reply" => "comments#create"
    end
  end
  resources :users do
    get "microposts" => "users#find_by_user"
    member do
      get :following, :followers
    end
    resources :messages, only: [ :index, :create, :destroy ]
  end
  resources :relationships, only: [ :create, :destroy ]
  root "static_pages#home"
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "test" => "static_pages#test"
  get "/signup" => "users#new"
  # login routes
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :microposts, only: [ :create, :destroy ]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/micropost.rb
# Micropost model
class Micropost < ApplicationRecord
  belongs_to :user
  belongs_to :parent, class_name: "Micropost", optional: true
  has_many :comments, class_name: "Micropost", foreign_key: "parent_id", dependent: :destroy
  has_many :reactions
  has_one_attached :image
  has_many_attached :images
  has_one_attached :file
  default_scope -> { order(created_at: :desc) }

  validates :content, presence: true
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png], message: "must be a valid image format" },
                            size: { less_than: 5.megabytes, message: "should be less than 5MB" }
  validates :file, content_type: { in: %w[pdf], message: "must be a valid image format" },
            size: { less_than: 5.megabytes, message: "should be less than 5MB" }
  def display_image
    image.variant(resize_to_limit: [ 500, 500 ])
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  include MicropostsHelper

  before_action :set_micropost, only: %i[ show edit update destroy react ]
  before_action :logged_in_user, only: [ :create, :destroy ]
  before_action :correct_user, only: :destroy

  # GET /microposts or /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1 or /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    @micropost.images.attach(params[:micropost][:images])
    respond_to do |format|
      if @micropost.save
        flash[:success] = "Micropost created!"
        format.html { redirect_to root_url, notice: "Micropost was successfully created." }
        format.json { render :show, status: :created, location: @micropost }
      else
        @feed_items = current_user.feed.paginate(page: params[:page])
        format.html { render "static_pages/home", status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: "Micropost was successfully updated." }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy!
    flash[:success] = "Micropost deleted"
    respond_to do |format|
      if request.referrer.nil? || request.referrer == micropost_url
        format.html { redirect_to root_url, status: :ok, notice: "Micropost was successfully destroyed." }
      else
        format.html { redirect_to request.referrer, status: :see_other, notice: "Micropost was successfully destroyed." }
      end
    end
  end

  def react
    reaction_type = params[:reaction_type]
    @reaction = Reaction.find_or_initialize_by(user_id: current_user.id, micropost_id: @micropost.id)
    respond_to do |format|
      if @reaction.persisted? && @reaction.reaction_type == reaction_type
        @reaction.destroy!
        format.turbo_stream {
          render_react_turbo_stream(turbo_stream)
        }
        format.html { redirect_to @micropost, status: :accepted }
      else
        @reaction.reaction_type = reaction_type
        if @reaction.save
          format.turbo_stream {
            render_react_turbo_stream(turbo_stream)
          }
          format.html { redirect_to @micropost, status: :created }
        else
          format.html { redirect_to @micropost, status: :unprocessable_entity }
        end
      end
    end
  end

  private

  def set_micropost
    @micropost = Micropost.find(params[:id] || params[:micropost_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: "Micropost not found"
  end

  # Only allow a list of trusted parameters through.
  def micropost_params
    params.require(:micropost).permit(:title, :content, :images, :file)
  end

  def correct_user
    redirect_to root_url unless @micropost&.user == current_user
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def current_user_react(micropost, user, type = "love")
    return false if micropost.nil?
    current_react = micropost.reactions.find_by(user_id: user.id)
    true if !current_react.nil? && current_react.reaction_type == type
  end

  def active_reaction_class(micropost, user)
    %w[ love sad angry ].find { |reaction| current_user_react(micropost, user, reaction) } || ""
  end

  def active_reaction_text(micropost, user)
    %w[ Love Sad Angry ].find { |reaction| current_user_react(micropost, user, reaction.downcase) }
  end

  def reaction_icon(reaction)
    case reaction
    when "love" then "grin-hearts"
    when "sad" then "frown"
    when "angry" then "angry"
    end
  end

  def render_react_turbo_stream(turbo_stream)
    render turbo_stream: [ turbo_stream.replace("reactions_micropost_#{@micropost.id}",
                                               partial: "shared/reaction_stats",
                                               locals: { micropost: @micropost }),
                          turbo_stream.replace("reaction_form_#{@micropost.id}",
                                               partial: "shared/reaction_form",
                                               locals: { micropost: @micropost }

                          ) ]
  end
end

app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div class="errors">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="micropost-content">
    <div >
      <%= link_to micropost.file.filename, micropost.file, disposition: 'preview' if micropost.file.attached?%>
    </div>
    <div>
      <% micropost.images.each_with_index do |image, index| %>
        <%= image_tag(image, class: "image-micropost" )%>
        <%= link_to "Download #{index + 1}", image, download: 'statements.json' if image.present?%>
      <% end %>
    </div>
  </span>
  <p class="content micropost-content">
    <%= micropost.content %>
  </p>
  <div>
    <%= image_tag micropost.image if micropost.image.attached? %>
  </div>
  <span>
    <%= link_to "show post", micropost %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/microposts/_micropost_show.html.erb
<div class="micropost-show">
  <div class="user-info">
    <span class="user">
      Author: <%= link_to micropost.user.name, micropost.user %>
    </span>
      <span class="micropost-content">
      <% if current_user?(micropost.user) %>
        <%= link_to "delete post", micropost, data: {turbo_method: :delete,  turbo_confirm: "You sure?" } %>
      <% end %>
    </span>
  </div>
  <div
    class="micropost-body"
  >
    <p class="content micropost-content">
      <%= micropost.content %>
    </p>
    <div >
      <%= image_tag micropost.image class: "image-micropost" if micropost.image.attached? %>
      <%= link_to micropost.file.filename, micropost.file, disposition: 'preview' if micropost.file.attached?%>
    </div>
    <div>
      <% micropost.images.each do |image| %>
        <%= image_tag(image, class: "image-micropost" )%>
      <% end %>
    </div>
    <p align="right" class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </p>
  </div>
  <div class="stats-container">
    <div class="reactions-stats" >
      <%= render "shared/reaction_stats", micropost: micropost %>
    </div>
    <% if micropost.comments.count > 0 %>
      <div class="comment-stats">
        <%= micropost.comments.count %>
        comments
      </div>
    <% end %>
  </div>
  <div class="reactions">
    <div class="reaction-post-main flex po-relative">
      <%= render "shared/reaction_form", micropost: micropost %>
    </div>
    <button class="reaction-icon">
      <i class="fa-regular fa-comment"></i>
      <span>Comment</span>
    </button>
  </div>
  <div >
    <%= render "shared/comment_form" %>
  </div>
  <div>
    <div id="microposts">
      <div id="microposts_<%= micropost.id %>"></div>
      <% micropost.comments.each do |comment| %>
        <%= render "shared/comment", micropost: comment %>
      <% end %>
    </div>
  </div>
</div>

app/views/microposts/edit.html.erb
<% content_for :title, "Editing micropost" %>

<h1>Editing micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Show this micropost", @micropost %> |
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/index.html.erb
<p class="notice"><%= notice %></p>

<% content_for :title, "Microposts" %>

<h1>Microposts</h1>

<div id="microposts">
  <% @microposts.each do |micropost| %>
    <%= render micropost %>
    <p>
      <%= link_to "Show this micropost", micropost %>
    </p>
  <% end %>
</div>

<%= link_to "New micropost", new_micropost_path %>

app/views/microposts/new.html.erb
<% content_for :title, "New micropost" %>

<h1>New micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/show.html.erb
<p class="notice"><%= notice %></p>

  <%= render "micropost_show", micropost: @micropost %>

<div>
  <% if current_user?(@micropost) %>
    <%= link_to "Edit this micropost", edit_micropost_path(@micropost) %> |
    <%= link_to "Back to microposts", microposts_path %>

    <%= button_to "Destroy this micropost", @micropost, method: :delete %>
  <% end %>
</div>